# -*- coding: utf-8 -*-
"""assignment3ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d86MuOZfRTVhH_q1USwuF3ziwuD3hdzh
"""

from google.colab import files
files.upload()

import zipfile

with zipfile.ZipFile("SoliData.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/data")

import os
import h5py

data_path = "/content/data/dsp"

file_name = os.listdir(data_path)[0]
print("Using file:", file_name)

with h5py.File(data_path+ "/"+ file_name,'r') as f:
    print("Keys:",list(f.keys()))

    data=f['ch0'][()]
    label= f['label'][()]

print("shape:",data.shape)
print("label:", label)

data = data.reshape(data.shape[0], 32, 32)

print(data.shape)
print(label)

import os
import h5py
import numpy as np

p = "/content/data/dsp"

print(len(os.listdir(p)))
print(os.listdir(p)[:5])

def fix_len(x):
    if len(x) > 50:
        return x[:50]
    else:
        pad = np.zeros((50 -len(x), 32, 32))
        return np.concatenate((x, pad), axis=0)

import torch

d = []
l = []
s = []

fl = sorted(os.listdir(p))

for f in fl:
    full = p + "/" + f

    with h5py.File(full, 'r') as h:
        dt =h['ch0'][()]
        lb= h['label'][()]

        dt =dt.reshape(dt.shape[0], 32, 32)
        dt= fix_len(dt)

        d.append(dt)

        try:
            l.append(lb[0][0])
        except:
            l.append(lb)

        parts = f.split("_")
        subject_id = int(parts[1])
        s.append(subject_id)

d =np.array(d)
d=torch.tensor(d, dtype=torch.float32)

l =torch.tensor(l, dtype=torch.long)
s =torch.tensor(s, dtype=torch.long)

print("data:", d.shape)
print("label:", l.shape)
print("session:", s.shape)
print("sessions:", torch.unique(s))

all_s = torch.unique(s)

half = len(all_s) // 2

fold1_s = all_s[:half]
fold2_s = all_s[half:]

print("fold1:", fold1_s)
print("fold2:", fold2_s)

tr = torch.isin(s, fold1_s)
te = torch.isin(s, fold2_s)

xtr = d[tr]
ytr = l[tr]
strr = s[tr]

xts = d[te]
yts = l[te]
sts = s[te]

tr2 = torch.isin(s, fold2_s)
te2 = torch.isin(s, fold1_s)

xtr_b = d[tr2]
ytr_b = l[tr2]
strr_b = s[tr2]

xts_b = d[te2]
yts_b = l[te2]
sts_b = s[te2]


print("fold A train:", xtr.shape, ytr.shape)
print("fold A test:", xts.shape, yts.shape)

print("fold B train:", xtr_b.shape, ytr_b.shape)
print("fold B test:", xts_b.shape, yts_b.shape)

import torch.nn as nn
import torch.optim as optim

class mm(nn.Module):
    def __init__(self):
        super().__init__()

        self.a = nn.Conv3d(1, 6, 3, padding=1)
        self.b = nn.MaxPool3d(2)

        self.c = nn.Conv3d(6, 12, 3, padding=1)
        self.d = nn.MaxPool3d(2)

        self.e = nn.Linear(12 * 12 * 8 * 8, 64)
        self.f = nn.Linear(64, 12)

    def forward(self, x):
        x = x.unsqueeze(1)

        x = self.b(torch.relu(self.a(x)))
        x = self.d(torch.relu(self.c(x)))

        x = x.view(x.size(0), -1)

        x = torch.relu(self.e(x))
        x = self.f(x)

        return x

m = mm()

lf = nn.CrossEntropyLoss()
op = optim.Adam(m.parameters(), lr=0.0003)

print("ok model")

bs = 16

for i in range(15):
    idx = torch.randperm(xtr.shape[0])
    xtr, ytr = xtr[idx], ytr[idx]

    tot = 0
    cor = 0
    losss = 0

    for j in range(0, len(xtr), bs):

        xx = xtr[j:j+bs]
        yy = ytr[j:j+bs]

        oo = m(xx)

        loss = lf(oo, yy)

        op.zero_grad()
        loss.backward()
        op.step()

        _, pp = torch.max(oo, 1)

        cor = cor + (pp == yy).sum().item()
        tot = tot + yy.size(0)
        losss = losss + loss.item()

    print("ep:", i, "loss:", losss, "train acc:", cor/tot)

bs = 16

tot = 0
cor = 0

with torch.no_grad():

    for j in range(0, len(xts), bs):

        xx = xts[j:j+bs]
        yy = yts[j:j+bs]

        oo = m(xx)

        _, pp = torch.max(oo, 1)

        cor = cor + (pp == yy).sum().item()
        tot = tot + yy.size(0)

print("test acc:", cor/tot)
torch.save(m.state_dict(), "/content/baseline_model.pt")
print("baseline model saved")

fg = [0, 1, 2, 3]
tot = 0
cor = 0

with torch.no_grad():
    for j in range(0, len(xts), bs):
        xx = xts[j:j+bs]
        yy = yts[j:j+bs]
        oo = m(xx)
        _, pp = torch.max(oo, 1)
        for k in range(len(yy)):
            if yy[k].item() in fg:
                tot = tot + 1
                if pp[k].item() == yy[k].item():
                    cor = cor + 1

print("baseline fine acc:", cor/tot)
print("fine total:", tot)

import numpy as np

def dann_lambda(epoch, total_epochs):
    p = epoch / total_epochs
    return float(2.0 / (1.0 + np.exp(-10.0 * p)) - 1.0)

class gr(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, temp1):
        ctx.temp1 = temp1
        return x.view_as(x)

    @staticmethod
    def backward(ctx, g):
        return -ctx.temp1 * g, None


class mm2(nn.Module):
    def __init__(self):
        super().__init__()

        self.a = nn.Conv3d(1, 6, 3, padding=1)
        self.b = nn.MaxPool3d(2)

        self.c = nn.Conv3d(6, 12, 3, padding=1)
        self.d = nn.MaxPool3d(2)

        self.e = nn.Linear(12 * 12 * 8 * 8, 64)

        self.f = nn.Linear(64, 12)
        self.g = nn.Linear(64, 16)

    def forward(self, x, temp1=0.2):
        x = x.unsqueeze(1)

        x = self.b(torch.relu(self.a(x)))
        x = self.d(torch.relu(self.c(x)))

        x = x.view(x.size(0), -1)

        x = torch.relu(self.e(x))

        out1 = self.f(x)

        temp2 = gr.apply(x, temp1)
        out2 = self.g(temp2)

        return out1, out2


m2 = mm2()

lf1 = nn.CrossEntropyLoss()
lf2 = nn.CrossEntropyLoss()

op2 = optim.Adam(m2.parameters(), lr=0.0003)

print("adv model ok")

bs = 16

for i in range(15):
    lam = dann_lambda(i, 15)
    idx = torch.randperm(xtr.shape[0])
    xtr, ytr, strr = xtr[idx], ytr[idx], strr[idx]
    tot = 0
    cor = 0
    losss = 0

    for j in range(0, len(xtr), bs):

        xx = xtr[j:j+bs]
        yy = ytr[j:j+bs]
        ss = strr[j:j+bs]

        o1, o2 = m2(xx, temp1=lam)

        l1 = lf1(o1, yy)
        l2 = lf2(o2, ss)

        loss = l1 + 0.2 * l2

        op2.zero_grad()
        loss.backward()
        op2.step()

        _, pp = torch.max(o1, 1)

        cor = cor + (pp == yy).sum().item()
        tot = tot + yy.size(0)
        losss = losss + loss.item()

    print("ep:", i, "loss:", losss, "train acc:", cor/tot)

bs = 16

tot = 0
cor = 0

with torch.no_grad():

    for j in range(0, len(xts), bs):

        xx = xts[j:j+bs]
        yy = yts[j:j+bs]

        o1, _ = m2(xx)

        _, pp = torch.max(o1, 1)

        cor = cor + (pp == yy).sum().item()
        tot = tot + yy.size(0)

print("adv test acc:", cor/tot)
torch.save(m2.state_dict(), "/content/dann_model.pt")
print("dann model saved")

print("Unique labels in dataset:", torch.unique(l).tolist())
print("Total samples per label:")
for lab in torch.unique(l):
    count = (l == lab).sum().item()
    print(f"  label {lab.item()} → {count} samples")

fg = [0, 1, 2, 3]

tot = 0
cor = 0

with torch.no_grad():

    for j in range(0, len(xts), bs):

        xx = xts[j:j+bs]
        yy = yts[j:j+bs]

        o1, _ = m2(xx)
        _, pp = torch.max(o1, 1)

        for k in range(len(yy)):
            if yy[k].item() in fg:
                tot = tot + 1
                if pp[k].item() == yy[k].item():
                    cor = cor + 1

print("adv fine acc:", cor/tot)
print("fine total:", tot)

class gen1(nn.Module):
    def __init__(self, noise_dim=100, num_classes=12):
        super().__init__()
        self.embed = nn.Embedding(num_classes, 32)
        self.a = nn.Linear(noise_dim + 32, 512)
        self.b = nn.Linear(512, 50 * 32 * 32)

    def forward(self, z, labels):
        emb = self.embed(labels)
        x = torch.cat([z, emb], dim=1)
        x = torch.relu(self.a(x))
        x = torch.tanh(self.b(x))
        return x.view(-1, 50, 32, 32)


class dis1(nn.Module):
    def __init__(self, num_classes=12):
        super().__init__()
        self.embed = nn.Embedding(num_classes, 50 * 32 * 32)
        self.a = nn.Conv3d(1, 6, 3, padding=1)
        self.b = nn.MaxPool3d(2)
        self.c = nn.Linear(6 * 25 * 16 * 16, 1)

    def forward(self, x, labels):
        label_map = self.embed(labels).view(-1, 50, 32, 32)
        x = x + 0.1 * label_map
        x = x.unsqueeze(1)
        x = self.b(torch.relu(self.a(x)))
        x = x.view(x.size(0), -1)
        return self.c(x)


gg = gen1()
dd = dis1()


lf_gan = nn.BCEWithLogitsLoss()

opg = optim.Adam(gg.parameters(), lr=0.0002)
opd = optim.Adam(dd.parameters(), lr=0.0002)

print("gan ok")

bs = 16

for i in range(5):

    totloss = 0

    for j in range(0, len(xtr), bs):

        realx = xtr[j:j+bs]
        realy = ytr[j:j+bs]
        B = realx.size(0)

        rr = torch.ones(B, 1)
        ff = torch.zeros(B, 1)


        z = torch.randn(B, 100)
        fakex = gg(z, realy)
        out_real = dd(realx, realy)
        out_fake = dd(fakex.detach(), realy)

        lossd = lf_gan(out_real, rr) + lf_gan(out_fake, ff)
        opd.zero_grad()
        lossd.backward()
        opd.step()


        z = torch.randn(B, 100)
        fakex = gg(z, realy)
        out_fake2 = dd(fakex, realy)

        lossg = lf_gan(out_fake2, rr)
        opg.zero_grad()
        lossg.backward()
        opg.step()

        totloss = totloss + lossd.item() + lossg.item()

    print("gan ep:", i, "loss:", totloss)

n_per_class = 100

fake_parts = []
lab_parts = []

with torch.no_grad():
    for cls in fg:
        z = torch.randn(n_per_class, 100)
        labels = torch.full((n_per_class,), cls, dtype=torch.long)
        fake = gg(z, labels)
        fake_parts.append(fake)
        lab_parts.append(labels)

fake1 = torch.cat(fake_parts, dim=0)
lab1 = torch.cat(lab_parts, dim=0)

xtr2 = torch.cat((xtr, fake1), dim=0)
ytr2 = torch.cat((ytr, lab1), dim=0)

print("old train:", xtr.shape, ytr.shape)
print("new train:", xtr2.shape, ytr2.shape)

m3 = mm()

lf3 = nn.CrossEntropyLoss()
op3 = optim.Adam(m3.parameters(), lr=0.0003)

bs = 16

for i in range(15):
    idx = torch.randperm(xtr2.shape[0])
    xtr2, ytr2 = xtr2[idx], ytr2[idx]

    tot = 0
    cor = 0
    losss = 0

    for j in range(0, len(xtr2), bs):

        xx = xtr2[j:j+bs]
        yy = ytr2[j:j+bs]

        oo = m3(xx)

        loss = lf3(oo, yy)

        op3.zero_grad()
        loss.backward()
        op3.step()

        _, pp = torch.max(oo, 1)

        cor = cor + (pp == yy).sum().item()
        tot = tot + yy.size(0)
        losss = losss + loss.item()

    print("gan cnn ep:", i, "loss:", losss, "train acc:", cor/tot)

bs = 16

tot = 0
cor = 0

with torch.no_grad():

    for j in range(0, len(xts), bs):

        xx = xts[j:j+bs]
        yy = yts[j:j+bs]

        oo = m3(xx)

        _, pp = torch.max(oo, 1)

        cor = cor + (pp == yy).sum().item()
        tot = tot + yy.size(0)

print("gan cnn test acc:", cor/tot)
torch.save(m3.state_dict(), "/content/cgan_cnn_model.pt")
print("cgan cnn model saved")

fg = [0, 1, 2, 3]

tot = 0
cor = 0

with torch.no_grad():

    for j in range(0, len(xts), bs):

        xx = xts[j:j+bs]
        yy = yts[j:j+bs]

        oo = m3(xx)
        _, pp = torch.max(oo, 1)

        for k in range(len(yy)):
            if yy[k].item() in fg:
                tot = tot + 1
                if pp[k].item() == yy[k].item():
                    cor = cor + 1

print("gan cnn fine acc:", cor/tot)
print("fine total:", tot)

m4 = mm2()

lf4a = nn.CrossEntropyLoss()
lf4b = nn.CrossEntropyLoss()

op4 = optim.Adam(m4.parameters(), lr=0.0003)

bs = 16
n_real = xtr.shape[0]

for i in range(15):
    lam = dann_lambda(i, 15)


    idx_aug = torch.randperm(xtr2.shape[0])
    xtr2, ytr2 = xtr2[idx_aug], ytr2[idx_aug]


    idx_real = torch.randperm(xtr.shape[0])
    xtr_r = xtr[idx_real]
    ytr_r = ytr[idx_real]
    strr_r = strr[idx_real]

    tot = 0
    cor = 0
    losss = 0

    for j in range(0, len(xtr2), bs):


        xx_g = xtr2[j:j+bs]
        yy_g = ytr2[j:j+bs]


        j2 = j % n_real
        xx_d = xtr_r[j2:j2+bs]
        ss_d = strr_r[j2:j2+bs]

        o1, _ = m4(xx_g, temp1=lam)
        _, o2 = m4(xx_d, temp1=lam)

        l1 = lf4a(o1, yy_g)
        l2 = lf4b(o2, ss_d)

        loss = l1 + 0.3 * l2

        op4.zero_grad()
        loss.backward()
        op4.step()

        _, pp = torch.max(o1, 1)

        cor = cor + (pp == yy_g).sum().item()
        tot = tot + yy_g.size(0)
        losss = losss + loss.item()

    print("both ep:", i, "loss:", losss, "train acc:", cor/tot)

bs = 16

tot = 0
cor = 0

with torch.no_grad():

    for j in range(0, len(xts), bs):

        xx = xts[j:j+bs]
        yy = yts[j:j+bs]

        o1, _ = m4(xx, temp1 =1.0)

        _, pp = torch.max(o1, 1)

        cor = cor + (pp == yy).sum().item()
        tot = tot + yy.size(0)

print("both test acc:", cor/tot)
torch.save(m4.state_dict(), "/content/unified_model.pt")
print("unified model saved")

fg = [0, 1, 2, 3]

tot = 0
cor = 0

with torch.no_grad():

    for j in range(0, len(xts), bs):

        xx = xts[j:j+bs]
        yy = yts[j:j+bs]

        o1, _ = m4(xx, temp1=1.0)
        _, pp = torch.max(o1, 1)

        for k in range(len(yy)):
            if yy[k].item() in fg:
                tot = tot + 1
                if pp[k].item() == yy[k].item():
                    cor = cor + 1

print("both fine acc:", cor/tot)
print("fine total:", tot)



















